name: Pylint Check

on:
  push:
    branches:
      - main  # Adjust this to your default branch name

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust as needed

      - name: Run Pylint
        run: pylint **/*.py
